### ISSUE TITLE
In Category filter, I dont want to operator suggestion in dropdown

### ISSUE THREAD

**Issue by vamshisai98** [siemens/ix#1446]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

In Category filter, I am using Equal Operator by default. But I see Not Equal Operator as suggestion in the drop down. Not able to disable it.

![Equal_operator](https://github.com/user-attachments/assets/bf08afec-9e27-45a0-bb93-eb9ed97480e9)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
<ix-category-filter id="category-filter-search__ix-category-filter" [placeholder]="placeholder"
      [repeatCategories]="repeatCategories" [categories]="categories" [filterState]="filterState"
      (categoryChanged)="handleCategoryChange($event)" (filterChanged)="handleFilterChange($event)"
      (inputChanged)="handleInputChange($event)"></ix-category-filter>


  public filterState: {tokens:[],categories:[]} = {
    tokens: [],
    categories: [],
  };
  public categories: Categories = {
    ID_1: {
      label: 'Applications',
      options: [],
    },
    ID_2: {
      label: 'DeviceTypes',
      options: [],
    },
  };
```

**Comment by matthiashader** [comment]
Hello @vamshisai98, thanks for reaching out. You can just overwrite the staticOperator property, like
`    <IxCategoryFilter
      placeholder="Filter by"
      repeatCategories={true}
      filterState={filter}
      categories={categories}
      staticOperator={LogicalFilterOperator.EQUAL}
    ></IxCategoryFilter>`
This way the "!=" isn't displayed anymore.

**Comment by vamshisai98** [comment]
Hey thanks, Tried that but I dont think its solving my issue. For instance this is how it is showing after I updated to adding staticOperator={LogicalFilterOperator.EQUAL
![Uploading Equal_operator.PNG…]()

**Comment by matthiashader** [comment]
Hello @vamshisai98. I got you now, currently there is no really nice solutio. I think one option that would pass the logic would be to set the statcOperator to "0", but I will create a ticket for this!

**Comment by matthiashader** [comment]
Hello @vamshisai98, this should be fixed with the latest version: 
![image](https://github.com/user-attachments/assets/c1b99342-7ba2-4f0e-baf6-1224757c010f)

**Comment by vamshisai98** [comment]
Hi @matthiashader ---> I have updated my ix version to - **2.5.0**.   I still the issue persist. Is there anything I need to change in the below code to resolve it? 

<ix-category-filter
      id="category-filter-search__ix-category-filter"
      [placeholder]="placeholder"
      [repeatCategories]="repeatCategories"
      [categories]="categories"
      [filterState]="filterState"
      (categoryChanged)="handleCategoryChange($event)"
      (filterChanged)="handleFilterChange($event)"
      (inputChanged)="handleInputChange($event)"
      label-categories="Select a category"
      **static-operator="LogicalFilterOperator.EQUAL"**
    ></ix-category-filter>
    
    I have tried       **static-operator="0"** as well

**Comment by nuke-ellington** [comment]
@vamshisai98 `staticOperator="Equal"` should work.
