### ISSUE TITLE
Input with icon has overlap issue inside drawer component

### ISSUE THREAD

**Issue by ugurbayraktarr** [siemens/ix#1551]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I have a simple component, that displays an input with an icon.
When I use this component inside a **Drawer** component, the text overlaps the icon.

![image](https://github.com/user-attachments/assets/f3a36306-9766-4626-a572-d251cef6ff0a)

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.5.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/ygj7zm-jzuhbw?file=src%2FApp.tsx
```

**Comment by kathrinschalber** [comment]
Has been fixed in 3.0!

**Comment by ugurbayraktarr** [comment]
> Has been fixed in 3.0!

@kathrinschalber Unfortunately, the issue is not fixed and still occurs in v3.2.0
[stackblitz url](https://stackblitz.com/edit/ygj7zm-zsix5jrt?file=src%2FApp.tsx)

**Comment by kathrinschalber** [comment]
Hi @ugurbayraktarr! Sorry for the confusion - you're right, the issue still occurs when using the input group inside a drawer. For this specific case, we'd recommend using our dedicated [ix-input](https://ix.siemens.io/docs/components/input/code) components instead, which should resolve the problem. If you still encounter issues with the ix-input component in drawers, please let us know and we'll investigate further.

PS: We also recommend using [panes](https://ix.siemens.io/docs/components/panes/guide) instead of drawers since they offer much more flexibility (which is why we will deprecate the drawer in a future release)

**Comment by GayatriK2002** [comment]
I've verified this, as this issue was assigned to me, this works fine on my end using ix V3.2.0. As @kathrinschalber mentioned, this component will be deprecated - please use Pane and ix-input instead. If you still need this fixed, we can connect to resolve it.
