### ISSUE TITLE
Tree -> CustomTreeNode does not register clicks on child element.

### ISSUE THREAD

**Issue by MasonVX** [siemens/ix#2098]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [x] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

If you use a CustomTreeNode und use html childelements, like a div or span in it. A click is not registered on the node, when you click for example on a text which is in a div element.

I already was investigating for a couple of hours about it, because I thought I did do the error. To give you a starter: https://github.com/siemens/ix/blob/db2bbf5e55d5f7aca2c9e255dae917b746048d09/packages/core/src/components/tree/tree.tsx#L364

You set a custom attribute on the host element. The clicked target, might not have this custom attribute, because it might be a div or something else in the custom node. The simplest solution would probably to iterate through the parents until you find your custom attribute. 

### What type of frontend framework are you seeing the problem on?

Angular (Standalone)

### On which version of the frontend framework are you experiencing the issue?

Does not matter, is everywhere

### Which version of iX do you use?

v3.2.0

### Code to produce this issue.

```shell
Try on you demo page: https://ix.siemens.io/docs/components/tree/code#properties

The selection is not registered when you click on the text in the CustomTreeNode. When you click next to the text, the click is registered.
```

**Comment by tgaugler** [comment]
when is it planned to inlcude this fix in IX 4.x?

**Comment by marvin-grvn** [comment]
Is there any update on this bug?
With ix v2 it was working fine

**Comment by ManeeshJaikumar** [comment]
Hello @marvingreeven, the issue has been fixed and will be available in the upcoming version.

**Comment by GauravJKshirsagar** [comment]
when is it planned to include this fix in IX 4.x ?

**Comment by marvin-grvn** [comment]
@ManeeshJaikumar The issue still occurs in v4.3.0
https://ix.siemens.io/demo/v2/preview/html/preview-examples/tree-custom.html?no-margin=true&theme=classic&colorSchema=light

**Comment by ManeeshJaikumar** [comment]
Hello @marvingreeven @GauravJKshirsagar , the fix for this particular issue is planned to be part of v4.4.0.
